substitutions:
  _REGION: us-central1
  _REPO: vesti-upzero
  _SERVICE_NAME: vesti-upzero
  _CATALOG_JOB_NAME: catalog-sync-job
  _COLOR_TERMS_JOB_NAME: color-terms-sync-job

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_USE_CLOUD_RUN_JOBS=true
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$BUILD_ID
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:latest
      - .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$BUILD_ID
      - --region=${_REGION}
      - --no-allow-unauthenticated

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - ${_CATALOG_JOB_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$BUILD_ID
      - --region=${_REGION}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - deploy
      - ${_COLOR_TERMS_JOB_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$BUILD_ID
      - --region=${_REGION}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:latest

options:
  logging: CLOUD_LOGGING_ONLY
